directml,cudaのダウンロードとデプロイを実装した
VOICEVOX/voicevox_additional_libraries pull request #1
Opened 2022-08-17 20:47 UTC by qwerty2501

directml,cudaのダウンロードとデプロイのCI実装です
cudaについて、対象環境でインストールを行う必要があるのでローカルで実行するスクリプトではなくCIでデプロイする形をとってます

2022-08-25 15:11 UTC, Hiroshiba requested changes
気持ち的にはapproveなのですが、もしよかったらということでいくつか提案しました！

2022-08-25 15:11 UTC, Hiroshiba commented on .github/workflows/download_and_deploy.yml
> +  VERSION: ${{ github.event.release.tag_name || github.event.inputs.version || 'DEBUG' }}
versionを引数に取れるworkflow_dispatchも、`on:`に追加して頂けると助かります！！

2022-08-25 15:11 UTC, Hiroshiba commented on .github/workflows/download_and_deploy.yml
> +  SKIP_UPLOADING_RELEASE_ASSET: ${{ secrets.SKIP_UPLOADING_RELEASE_ASSET || '1' }}
SKIP_UPLOADING_RELEASE_ASSETはプライベートリポジトリがある場合に有用ですが、今回だと無いほうがありがたい感じです･･･！

2022-08-25 15:11 UTC, Hiroshiba commented on .github/workflows/download_and_deploy.yml
> +      CUDA_VERSION: ${{ matrix.cuda_version || '11.6.0' }}
別にこのままでもOKなのですが、VERSIONと同じenvのとこにバージョンが定義されていると、修正が必要な箇所を１箇所に集められるので嬉しいかもです。

2022-08-25 15:16 UTC, qwerty2501 commented on docs/licenses/cuda/NVIDIA_SLA_cuDNN_Support.txt
> +NVIDIA SOFTWARE LICENSE AGREEMENT
voicevox engineのrepositoryところで管理してたものですね

2022-08-25 15:22 UTC, qwerty2501 commented on .github/workflows/download_and_deploy.yml
> +      CUDA_VERSION: ${{ matrix.cuda_version || '11.6.0' }}
それやりたかったんですが、愚直に  ${{ matrix.cuda_version ||  env.LATEST_CUDA_VERSION }} みたいに書くとエラーになった記憶があります。なので泣く泣くここに・・・

2022-08-25 15:23 UTC, qwerty2501 commented on .github/workflows/download_and_deploy.yml
> +  SKIP_UPLOADING_RELEASE_ASSET: ${{ secrets.SKIP_UPLOADING_RELEASE_ASSET || '1' }}
fixed

2022-08-25 15:29 UTC, qwerty2501 commented on .github/workflows/download_and_deploy.yml
> +      CUDA_VERSION: ${{ matrix.cuda_version || '11.6.0' }}
あ、 `matrix.cuda_version` のように matrixで個別にバージョン設定する必要ないのでは？ということですかね？
確かにrootのenvに設定することもできますが、それだと例えばWindowsとLinuxで違うcuda versionを設定したい場合にはちょっと困るかなと。そうそうないですが、Winodws版の最新版cudaにのみ問題がある場合などはそういう対応が必要になると思います。

2022-08-25 15:38 UTC, Hiroshiba commented on docs/licenses/cuda/NVIDIA_SLA_cuDNN_Support.txt
> +NVIDIA SOFTWARE LICENSE AGREEMENT
なるほどです、ありがとうございます！

2022-08-25 15:42 UTC, Hiroshiba commented on .github/workflows/download_and_deploy.yml
> +      CUDA_VERSION: ${{ matrix.cuda_version || '11.6.0' }}
あーーーなるほど、おっしゃるとおりだと思います。
となると、matrixのとこにcuda_version `11.6.0`を設定して、そこを変えるようにすると一元管理できて良さそうです。

matrixの記法はちょっとややこしいのですが、たぶんこう書けば全部がデフォルト値`11.6.0`になり、あとあと個別に設定することもできると思います。
```yaml
    strategy:
      matrix:
        cuda_version: [11.6.0]
        include:
          - os: windows-latest
            artifact_name: windows-x64
            cudnn_download_url: https://developer.download.nvidia.com/compute/redist/cudnn/v8.4.1/local_installers/11.6/cudnn-windows-x86_64-8.4.1.50_cuda11.6-archive.zip
          - os: ubuntu-latest
            artifact_name: linux-x64
            cudnn_download_url: https://developer.download.nvidia.com/compute/redist/cudnn/v8.4.1/local_installers/11.6/cudnn-linux-x86_64-8.4.1.50_cuda11.6-archive.tar.xz
```
https://docs.github.com/ja/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations

2022-08-25 15:43 UTC, qwerty2501 commented on .github/workflows/download_and_deploy.yml
> +      CUDA_VERSION: ${{ matrix.cuda_version || '11.6.0' }}
なるほど。学びです

2022-08-25 16:07 UTC, qwerty2501 commented on .github/workflows/download_and_deploy.yml
> +      CUDA_VERSION: ${{ matrix.cuda_version || '11.6.0' }}
うーん、これだと Windowsがリリースされなくなってしまうようです・・・
https://github.com/qwerty2501/voicevox_additional_libraries/releases/tag/0.0.11-all-download-test

2022-08-25 16:53 UTC, qwerty2501 commented on .github/workflows/download_and_deploy.yml
> +      CUDA_VERSION: ${{ matrix.cuda_version || '11.6.0' }}
includeだと良くなかったんで便宜的にartifactというfieldを作ってそこに各artifact情報を持たせるようにしたらうまく行きました

https://github.com/qwerty2501/voicevox_additional_libraries/releases/tag/0.0.13-test-all-download

2022-08-26 15:30 UTC, Hiroshiba commented on .github/workflows/download_and_deploy.yml
> +      CUDA_VERSION: ${{ matrix.cuda_version || '11.6.0' }}
あ！すみません、たぶんこう書かないとダメかもです･･･

```yaml
        cuda_version: ["11.6.0"]
        os: [windows-latest, ubuntu-latest]  # ←　ここが追加されました
        artifact:
          - os: windows-latest
            artifact_name: windows-x64
            cudnn_download_url: https://developer.download.nvidia.com/compute/redist/cudnn/v8.4.1/local_installers/11.6/cudnn-windows-x86_64-8.4.1.50_cuda11.6-archive.zip
          - os: ubuntu-latest
            artifact_name: linux-x64
            cudnn_download_url: https://developer.download.nvidia.com/compute/redist/cudnn/v8.4.1/local_installers/11.6/cudnn-linux-x86_64-8.4.1.50_cuda11.6-archive.tar.xz
```

これだったら
```yaml
        include:  # 戻しました
          - os: windows-latest
            artifact_name: windows-x64
            cudnn_download_url: https://developer.download.nvidia.com/compute/redist/cudnn/v8.4.1/local_installers/11.6/cudnn-windows-x86_64-8.4.1.50_cuda11.6-archive.zip
            cuda_version: "11.6.0"  # 追加
          - os: ubuntu-latest
            artifact_name: linux-x64
            cudnn_download_url: https://developer.download.nvidia.com/compute/redist/cudnn/v8.4.1/local_installers/11.6/cudnn-linux-x86_64-8.4.1.50_cuda11.6-archive.tar.xz
            cuda_version: "11.6.0"  # 追加
```

こうのほうが良いかなぁ･･･。

artifactを挟む形もなるほどです！！

2022-08-26 15:34 UTC, qwerty2501 commented on .github/workflows/download_and_deploy.yml
> +      CUDA_VERSION: ${{ matrix.cuda_version || '11.6.0' }}
まあ数も少ないですし、個別にバージョン設定する感じにしときますか

2022-08-26 16:44 UTC, qwerty2501 commented on .github/workflows/download_and_deploy.yml
> +      CUDA_VERSION: ${{ matrix.cuda_version || '11.6.0' }}
個別にバージョン設定するようにしました

2022-08-26 17:29 UTC, Hiroshiba approved these changes
LGTM！！

この後の作業としては、リリースを作れば良い感じですよね👀
バージョンどうしましょう。適当に、コアとかとマイナーバージョンまで合わせて、パッチ番号をインクリメントとか…？

2022-08-26 22:08 UTC, qwerty2501 commented
coreとバージョンを揃えてしまうと例えば扱うライブラリを変更するなどの大きめの変更を表現できなくなってしまうのでcoreとバージョンは合わせなくてよいのでは

2022-08-28 08:54 UTC, qwerty2501 commented
そういえばこれあとだれがapproveできるんでしょうか？

2022-08-28 08:59 UTC, Hiroshiba commented
バージョンに関して、なるほどです。
適当にバージョン上げしていきますか…！

マージします！

2022-08-28 09:00 UTC, merged

2022-08-28 09:01 UTC, qwerty2501 commented
@Hiroshiba merge後リリースの作成お手数ですがお願いします

2022-08-28 09:08 UTC, Hiroshiba commented
了解です！！

2022-08-28 09:09 UTC, Hiroshiba commented
https://github.com/VOICEVOX/voicevox_additional_libraries/releases/tag/0.1.0

2022-08-28 09:10 UTC, qwerty2501 commented
ありがとうございます！